# -*- coding: utf-8 -*-
"""credit_risk_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mPCwg5SCbZCcLPh-2H-bgNN1V_DXe3c
"""

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load dataset
data = pd.read_csv("/content/Task 3 and 4_Loan_Data.csv")

# Display first rows
print(data.head())

# Features (independent variables)
X = data.drop("default", axis=1)

# Target variable
y = data["default"]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

# Predict defaults
predictions = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, predictions)
print("Model Accuracy:", accuracy)

# Function to calculate expected loss
def expected_loss(loan_amount, borrower_data):

    # Predict probability of default
    pd_value = model.predict_proba([borrower_data])[0][1]

    # Recovery rate = 10%
    recovery_rate = 0.10

    # Loss Given Default
    lgd = 1 - recovery_rate

    # Expected Loss Formula
    expected_loss_value = pd_value * lgd * loan_amount

    return expected_loss_value

# Example borrower
example_borrower = X.iloc[0].tolist()

# Example calculation
loss = expected_loss(10000, example_borrower)

print("Expected Loss:", loss)