# -*- coding: utf-8 -*-
"""fico_score_bucketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VbceBOTAbojxsL1hIF_zs2ifrfezaB1
"""

import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv("/content/Task 3 and 4_Loan_Data.csv")

# Display first rows
print(data.head())

# Create 5 buckets based on FICO scores
data['fico_bucket'] = pd.qcut(
    data['fico_score'],
    q=5,
    labels=[5,4,3,2,1]
)

# Calculate probability of default for each bucket
bucket_summary = data.groupby('fico_bucket')['default'].mean()

print("\nProbability of Default by Bucket:")
print(bucket_summary)

# Function to assign rating
def assign_rating(fico_score):

    bucket = pd.qcut(
        data['fico_score'],
        q=5,
        labels=[5,4,3,2,1]
    )

    # Find nearest matching bucket
    temp = pd.DataFrame({
        'fico_score': data['fico_score'],
        'rating': bucket
    })

    closest = temp.iloc[
        (temp['fico_score'] - fico_score).abs().argsort()[:1]
    ]

    return int(closest['rating'].values[0])

# Example usage
example_score = 720
rating = assign_rating(example_score)

print(f"\nFICO Score: {example_score}")
print(f"Assigned Rating: {rating}")