# -*- coding: utf-8 -*-
"""gas_storage_pricing_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0p0oTEkdnDKMppLKaV1dPLQ6baLGM9a
"""

# Gas Storage Contract Pricing Model

def price_gas_contract(
    injection_price,
    withdrawal_price,
    volume,
    storage_cost_per_month,
    storage_months,
    injection_cost,
    withdrawal_cost,
    transport_cost
):

    # Total buying cost
    purchase_cost = injection_price * volume

    # Total selling revenue
    selling_revenue = withdrawal_price * volume

    # Storage costs
    total_storage_cost = storage_cost_per_month * storage_months

    # Total operational costs
    operational_costs = (
        injection_cost +
        withdrawal_cost +
        transport_cost
    )

    # Final contract value
    contract_value = (
        selling_revenue
        - purchase_cost
        - total_storage_cost
        - operational_costs
    )

    return contract_value


# Example test case

contract_price = price_gas_contract(
    injection_price=2,
    withdrawal_price=3,
    volume=1000000,
    storage_cost_per_month=100000,
    storage_months=4,
    injection_cost=10000,
    withdrawal_cost=10000,
    transport_cost=100000
)

print("Estimated Contract Value: $", contract_price)