# -*- coding: utf-8 -*-
"""natural_gas_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNoUrVIdTWUvD5fUNGyrjcXhLg4wnlBH
"""



"""# New Section"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from datetime import datetime

# Load CSV file
data = pd.read_csv("Nat_Gas.csv")

# Convert dates into datetime format
data['Dates'] = pd.to_datetime(data['Dates'])

# Sort values by date
data = data.sort_values('Dates')

# Plot historical prices
plt.figure(figsize=(12,6))
plt.plot(data['Dates'], data['Prices'], marker='o')
plt.title("Natural Gas Prices Over Time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.grid(True)
plt.show()

# Convert dates into numeric format
x = data['Dates'].map(datetime.toordinal)
y = data['Prices']

# Interpolation function
f = interp1d(x, y, kind='linear', fill_value='extrapolate')

# Function to estimate prices
def estimate_price(input_date):

    date = pd.to_datetime(input_date)
    date_ordinal = date.toordinal()

    predicted_price = float(f(date_ordinal))

    return round(predicted_price, 2)

# Example outputs
print("Estimated price on 2023-06-15:", estimate_price("2023-06-15"))
print("Estimated price on 2025-03-31:", estimate_price("2025-03-31"))